import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Fofofa News | Entrar",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="p-10">
        {children}
      </div>
  );
}
